### ISSUE TITLE
Chat is not working - responding as if I'm inputting blank statements

### ISSUE THREAD

**Issue by jenb2** [NIH-OIR/CHIRP_LLM#26]
The chat does not seem to be responding to my prompts. Is answering me as if I'm just sending blank statements

![image](https://github.com/user-attachments/assets/a8ea5d4d-3d84-459a-b227-c089aa75455e)
![Screenshot 2024-08-22 094546](https://github.com/user-attachments/assets/c3221a3a-4a17-48bc-bb4b-06152bc9788f)

**Comment by lilyfanNIH** [comment]
This issue was cause by PI scrubber implement with following error msg:
[Fri Aug 23 14:19:32.939141 2024] [php:notice] [pid 457185] [client 10.245.85.214:64498] python command: python3 /var/www/chirp.od.nih.gov/scrubber.py "hello", referer: https://chirp.od.nih.gov/579DF28A47AE4CD8B72973347323385A
Traceback (most recent call last):
  File "/var/www/chirp.od.nih.gov/scrubber.py", line 1, in <module>
    import scrubadub
=============Solution==============
running following command to install scrubadub globally:
sudo python3 -m pip config set global.break-system-packages true
sudo pip3 install scrubadub

**Comment by lilyfanNIH** [comment]
uninstalled scrbadub module

sudo pip3 uninstall scrubadub
